// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Alerts = sequelize.define('alerts', {
    id: {
      type: DataTypes.UUID,
      primaryKey: true,
      defaultValue: Sequelize.literal('gen_random_uuid()'),
      allowNull: false,
    },
    type: {
      type: DataTypes.STRING,
    },
    severity: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    status: {
      type: DataTypes.STRING,
      defaultValue: "open",
    },
    triggeredAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('now()'),
    },
    details: {
      type: DataTypes.JSONB,
      defaultValue: {},
    },
  }, {
    tableName: 'alerts',
    underscored: true,
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  Alerts.associate = (models) => {
    Alerts.belongsTo(models.accounts, {
      foreignKey: {
        name: 'accountIdKey',
        field: 'account_id',
      },
      as: 'account',
    });
    Alerts.belongsTo(models.customers, {
      foreignKey: {
        name: 'customerIdKey',
        field: 'customer_id',
      },
      as: 'customer',
    });
    Alerts.belongsToMany(models.cases, {
      through: 'caseLinks',
      foreignKey: 'alert_id',
      otherKey: 'case_id',
      as: 'casesThroughCaseLinks',
    });
  };

  return Alerts;
};
