// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Applications = sequelize.define('applications', {
    id: {
      type: DataTypes.UUID,
      primaryKey: true,
      defaultValue: Sequelize.literal('gen_random_uuid()'),
      allowNull: false,
    },
    customerId: {
      type: DataTypes.UUID,
    },
    status: {
      type: DataTypes.STRING,
      defaultValue: "submitted",
    },
    riskScore: {
      type: DataTypes.INTEGER,
      defaultValue: 0,
    },
    kycLevel: {
      type: DataTypes.STRING,
      defaultValue: "standard",
    },
    sanctionsHits: {
      type: DataTypes.INTEGER,
      defaultValue: 0,
    },
    submittedAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('now()'),
    },
    reviewer: {
      type: DataTypes.STRING,
    },
    notes: {
      type: DataTypes.STRING,
    },
  }, {
    tableName: 'applications',
    underscored: true,
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  Applications.associate = (models) => {
    Applications.hasMany(models.documents, {
      foreignKey: {
        name: 'applicationIdKey',
        field: 'application_id',
      },
      as: 'documents',
    });
  };

  return Applications;
};
