// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const CaseLinks = sequelize.define('caseLinks', {
  }, {
    tableName: 'case_links',
    underscored: true,
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });
  CaseLinks.removeAttribute('id');
  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  CaseLinks.associate = (models) => {
    CaseLinks.belongsTo(models.alerts, {
      foreignKey: {
        name: 'alertIdKey',
        field: 'alert_id',
      },
      as: 'alert',
    });
    CaseLinks.belongsTo(models.cases, {
      foreignKey: {
        name: 'caseIdKey',
        field: 'case_id',
      },
      as: 'case',
    });
  };

  return CaseLinks;
};
